[package]
name = "clubdarn"
version = "0.1.0"
authors = ["Walfie <walfington@gmail.com>"]

[dependencies]
clippy = {version = "*", optional = true}

reqwest = "0.4"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"

[features]
default = []

